// Code generated by genpacket.go. DO NOT EDIT.

package traffic

import (
	"bytes"
	"encoding/binary"
	"io"

	"github.com/wizzymore/tcp-go/reader"
)

func (p *IAmCameraPacket) Marshal() (b []byte, err error) {
	buff := bytes.Buffer{}
	err = buff.WriteByte(p.Opcode())
	if err != nil {
		return
	}

	err = binary.Write(&buff, binary.BigEndian, p.Road)
	if err != nil {
		return
	}

	err = binary.Write(&buff, binary.BigEndian, p.Mile)
	if err != nil {
		return
	}

	err = binary.Write(&buff, binary.BigEndian, p.Limit)
	if err != nil {
		return
	}

	b = buff.Bytes()
	return
}

func (p *IAmCameraPacket) Unmarshal(r io.Reader) (err error) {

	err = reader.ReadB(r, &p.Road)
	if err != nil {
		return
	}

	err = reader.ReadB(r, &p.Mile)
	if err != nil {
		return
	}

	err = reader.ReadB(r, &p.Limit)
	if err != nil {
		return
	}

	return
}

func (p *IAmDispatcherPacket) Marshal() (b []byte, err error) {
	buff := bytes.Buffer{}
	err = buff.WriteByte(p.Opcode())
	if err != nil {
		return
	}

	err = buff.WriteByte(byte(len(p.Roads)))
	if err != nil {
		return
	}
	err = binary.Write(&buff, binary.BigEndian, p.Roads)
	if err != nil {
		return
	}

	b = buff.Bytes()
	return
}

func (p *IAmDispatcherPacket) Unmarshal(r io.Reader) (err error) {

	{
		var length byte
		length, err = reader.ReadByte(r)
		if err != nil {
			return
		}
		buf := make([]uint16, length)
		err = reader.ReadB(r, buf)
		if err != nil {
			return
		}
		p.Roads = buf
	}

	return
}

func (p *ErrorPacket) Marshal() (b []byte, err error) {
	buff := bytes.Buffer{}
	err = buff.WriteByte(p.Opcode())
	if err != nil {
		return
	}

	err = buff.WriteByte(byte(len(p.Message)))
	if err != nil {
		return
	}
	n, err := buff.WriteString(p.Message)
	if err != nil {
		return
	}
	if n != len(p.Message) {
		err = io.ErrUnexpectedEOF
		return
	}

	b = buff.Bytes()
	return
}

func (p *ErrorPacket) Unmarshal(r io.Reader) (err error) {

	{
		var length byte
		length, err = reader.ReadByte(r)
		if err != nil {
			return
		}
		var buf []byte
		buf, err = reader.ReadN(r, int(length))
		if err != nil {
			return
		}
		p.Message = string(buf)
	}

	return
}

func (p *PlatePacket) Marshal() (b []byte, err error) {
	buff := bytes.Buffer{}
	err = buff.WriteByte(p.Opcode())
	if err != nil {
		return
	}

	err = buff.WriteByte(byte(len(p.Plate)))
	if err != nil {
		return
	}
	n, err := buff.WriteString(p.Plate)
	if err != nil {
		return
	}
	if n != len(p.Plate) {
		err = io.ErrUnexpectedEOF
		return
	}

	err = binary.Write(&buff, binary.BigEndian, p.Timestamp)
	if err != nil {
		return
	}

	b = buff.Bytes()
	return
}

func (p *PlatePacket) Unmarshal(r io.Reader) (err error) {

	{
		var length byte
		length, err = reader.ReadByte(r)
		if err != nil {
			return
		}
		var buf []byte
		buf, err = reader.ReadN(r, int(length))
		if err != nil {
			return
		}
		p.Plate = string(buf)
	}

	err = reader.ReadB(r, &p.Timestamp)
	if err != nil {
		return
	}

	return
}

func (p *TicketPacket) Marshal() (b []byte, err error) {
	buff := bytes.Buffer{}
	err = buff.WriteByte(p.Opcode())
	if err != nil {
		return
	}

	err = buff.WriteByte(byte(len(p.Plate)))
	if err != nil {
		return
	}
	n, err := buff.WriteString(p.Plate)
	if err != nil {
		return
	}
	if n != len(p.Plate) {
		err = io.ErrUnexpectedEOF
		return
	}

	err = binary.Write(&buff, binary.BigEndian, p.Road)
	if err != nil {
		return
	}

	err = binary.Write(&buff, binary.BigEndian, p.Mile1)
	if err != nil {
		return
	}

	err = binary.Write(&buff, binary.BigEndian, p.Timestamp1)
	if err != nil {
		return
	}

	err = binary.Write(&buff, binary.BigEndian, p.Mile2)
	if err != nil {
		return
	}

	err = binary.Write(&buff, binary.BigEndian, p.Timestamp2)
	if err != nil {
		return
	}

	err = binary.Write(&buff, binary.BigEndian, p.Speed)
	if err != nil {
		return
	}

	b = buff.Bytes()
	return
}

func (p *TicketPacket) Unmarshal(r io.Reader) (err error) {

	{
		var length byte
		length, err = reader.ReadByte(r)
		if err != nil {
			return
		}
		var buf []byte
		buf, err = reader.ReadN(r, int(length))
		if err != nil {
			return
		}
		p.Plate = string(buf)
	}

	err = reader.ReadB(r, &p.Road)
	if err != nil {
		return
	}

	err = reader.ReadB(r, &p.Mile1)
	if err != nil {
		return
	}

	err = reader.ReadB(r, &p.Timestamp1)
	if err != nil {
		return
	}

	err = reader.ReadB(r, &p.Mile2)
	if err != nil {
		return
	}

	err = reader.ReadB(r, &p.Timestamp2)
	if err != nil {
		return
	}

	err = reader.ReadB(r, &p.Speed)
	if err != nil {
		return
	}

	return
}

func (p *WantHeartbeatPacket) Marshal() (b []byte, err error) {
	buff := bytes.Buffer{}
	err = buff.WriteByte(p.Opcode())
	if err != nil {
		return
	}

	err = binary.Write(&buff, binary.BigEndian, p.Interval)
	if err != nil {
		return
	}

	b = buff.Bytes()
	return
}

func (p *WantHeartbeatPacket) Unmarshal(r io.Reader) (err error) {

	err = reader.ReadB(r, &p.Interval)
	if err != nil {
		return
	}

	return
}

func (p *HeartbeatPacket) Marshal() (b []byte, err error) {
	buff := bytes.Buffer{}
	err = buff.WriteByte(p.Opcode())
	if err != nil {
		return
	}

	b = buff.Bytes()
	return
}

func (p *HeartbeatPacket) Unmarshal(r io.Reader) (err error) {

	return
}
