package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"slices"
	"strings"
	"text/template"
)

var fileFlag = flag.String("file", "", "File to generate types for")
var typesFlag = flag.String("types", "", "Types to take in consdieration. Ex: Packet1,Packet2")

type Field struct {
	Name string
	Type string
}

type StructInfo struct {
	Name   string
	Fields []Field
}

func main() {
	flag.Parse()
	if *fileFlag == "" {
		flag.Usage()
		return
	}
	types := []string{}
	for t := range strings.SplitSeq(*typesFlag, ",") {
		ty := strings.TrimSpace(t)
		if len(ty) > 0 {
			types = append(types, strings.TrimSpace(t))
		}
	}
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, *fileFlag, nil, parser.AllErrors)
	if err != nil {
		log.Fatal(err)
	}

	var structs []StructInfo

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}

		for _, spec := range genDecl.Specs {
			tspec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			s, ok := tspec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			structInfo := StructInfo{
				Name: tspec.Name.Name,
			}

			if len(types) > 0 {
				_, found := slices.BinarySearch(types, structInfo.Name)
				if !found {
					continue
				}
			}

			for _, field := range s.Fields.List {
				for _, name := range field.Names {
					structInfo.Fields = append(structInfo.Fields, Field{
						Name: name.Name,
						Type: exprToString(field.Type),
					})
				}
			}

			structs = append(structs, structInfo)
		}
	}

	out, _ := os.Create(fmt.Sprintf("%s_gen.go", (*fileFlag)[0:len(*fileFlag)-3]))
	defer out.Close()
	tmpl.Execute(out, map[string]any{"structs": structs, "package": file.Name})
}

func exprToString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.ArrayType:
		// Currently only support slices
		if t.Len == nil {
			return "[]" + exprToString(t.Elt)
		}
		return ""
	default:
		return ""
	}
}

var tmpl = template.Must(template.New("").Parse(`// Code generated by genpacket.go. DO NOT EDIT.

package {{.package}}

import (
	"bytes"
	"encoding/binary"
	"io"

	"github.com/wizzymore/tcp-go/reader"
)
{{range .structs}}
func (p *{{.Name}}) Marshal() (b []byte, err error) {
	buff := bytes.Buffer{}
	err = buff.WriteByte(p.Opcode())
	if err != nil {
		return
	}
{{range .Fields}}
	{{- if eq .Type "string"}}
	err = buff.WriteByte(byte(len(p.{{.Name}})))
	if err != nil {
		return
	}
	n, err := buff.WriteString(p.{{.Name}})
	if err != nil {
		return
	}
	if n != len(p.{{.Name}}) {
		err = io.ErrUnexpectedEOF
		return
	}
	{{- else if or (eq .Type "[]int64") (eq .Type "[]int32") (eq .Type "[]int16") (eq .Type "[]int8") (eq .Type "[]uint64") (eq .Type "[]uint32") (eq .Type "[]uint16") (eq .Type "[]uint8")}}
	err = buff.WriteByte(byte(len(p.{{.Name}})))
	if err != nil {
		return
	}
	err = binary.Write(&buff, binary.BigEndian, p.{{.Name}})
	if err != nil {
		return
	}
	{{- else if or (eq .Type "int64") (eq .Type "int32") (eq .Type "int16") (eq .Type "int8") (eq .Type "uint64") (eq .Type "uint32") (eq .Type "uint16") (eq .Type "uint8")}}
	err = binary.Write(&buff, binary.BigEndian, p.{{.Name}})
	if err != nil {
		return
	}
	{{- else}}
	panic("Provided unsupported type {{.Type}} for {{.Name}}")
	{{- end}}
{{end}}
	b = buff.Bytes()
	return
}

func (p *{{.Name}}) Unmarshal(r io.Reader) (err error) {
{{range .Fields}} {{- if eq .Type "string"}}
	{
		var length byte
		length, err = reader.ReadByte(r)
		if err != nil {
			return
		}
		var buf []byte
		buf, err = reader.ReadN(r, int(length))
		if err != nil {
			return
		}
		p.{{.Name}} = string(buf)
	}
	{{- else if or (eq .Type "[]int64") (eq .Type "[]int32") (eq .Type "[]int16") (eq .Type "[]int8") (eq .Type "[]uint64") (eq .Type "[]uint32") (eq .Type "[]uint16") (eq .Type "[]uint8")}}
	{
		var length byte
		length, err = reader.ReadByte(r)
		if err != nil {
			return
		}
		buf := make([]uint16, length)
		err = reader.ReadB(r, buf)
		if err != nil {
			return
		}
		p.{{.Name}} = buf
	}
	{{- else if or (eq .Type "int64") (eq .Type "int32") (eq .Type "int16") (eq .Type "int8") (eq .Type "uint64") (eq .Type "uint32") (eq .Type "uint16") (eq .Type "uint8")}}
	err = reader.ReadB(r, &p.{{.Name}})
	if err != nil {
		return
	}
	{{- else}}
	panic("Provided unsupported type {{.Type}} for {{.Name}}")
	{{- end}}
{{end}}
	return
}
{{end}}`))
